### PR TITLE
Helm command to fetch chart needs to be corrected

### PR DESCRIPTION
**Pull request by bennythejudge**
The `helm fetch` example doesn't work:

```
 helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "ibmcase" chart repository
...Successfully got an update from the "ibm" chart repository
...Successfully got an update from the "ibm-charts" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
```

```
helm fetch ibm-charts/ibmcloud-block-storage-plugin
Error: chart "ibmcloud-block-storage-plugin" matching  not found in ibm-charts index. (try 'helm repo update'). no chart name found
```

```
helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Corrected with what seems the right command

### CODE REVIEW

**Comment by Nadine2016** [comment]
@bennythejudge I saw that you used the `ibm-charts` repo, but it is actually `iks-charts` as mentioned in the documentation. Please try that.

**Comment by bennythejudge** [comment]
I forgot to show the error I got when I tried to use that:

```
helm fetch iks-charts/ibmcloud-block-storage-plugin
Error: repo iks-charts not found
```

**Comment by Nadine2016** [comment]
@bennythejudge you have to add the repo with helm repo add iks-charts https://icr.io/helm/iks-charts

**Comment by bennythejudge** [comment]
thanks, it works as described in the instructions. apologies for the pointless PR

**Pull request closed without merging**
